スタンプ
traP-jp/h23w_01-frontend pull request #15
Opened 2023-12-14 15:45 UTC by ikura-hamu

スタンプを画面に置けるようになった。
traQから画像を直接持ってくるためにnext.config.jsをいじったので、後で変える必要がある。

2023-12-14 16:23 UTC, mehm8128 requested changes

2023-12-14 16:23 UTC, mehm8128 commented on src/features/traq/stamps.ts
> +}
![should](https://img.shields.io/badge/review-should-important.svg)
型は基本的にPascalCaseでお願いします

2023-12-14 16:23 UTC, mehm8128 commented on src/features/fabric/components/stamps/stampSelector.tsx
> +							height={128}
![fyi](https://img.shields.io/badge/review-fyi-informational.svg)
多分そんなに問題ないですが、ユーザーアイコンは256でスタンプは128で返ってくるっぽいですね

2023-12-14 16:23 UTC, mehm8128 commented on src/features/fabric/components/stamps/stampSelector.tsx
> +						)}
![fyi](https://img.shields.io/badge/review-fyi-informational.svg)
`lib/utils`の`cn`ってやつ使うと多分もうちょっときれいに書けます

2023-12-14 16:23 UTC, mehm8128 commented on src/features/fabric/components/stamps/stampSelector.tsx
![should](https://img.shields.io/badge/review-should-important.svg)
ファイル名PascalCaseでお願いします

2023-12-14 16:23 UTC, mehm8128 commented on src/features/fabric/components/stamps/stampSelector.tsx
> +						key={stamp.name}
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
多分問題ないけど`stamp.id`の方が自然な気がします

2023-12-14 16:23 UTC, mehm8128 commented on src/features/fabric/components/stamps/useStamp.ts
> +}
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
`lib`とかに共通化するとよさそうです

2023-12-14 16:23 UTC, mehm8128 commented on src/features/fabric/components/stamps/util.ts
> +	}
![ask](https://img.shields.io/badge/review-ask-blue.svg)
ここでこの関数終了してユーザーアイコン全部returnしちゃってそうだけどこれで合ってますか？

2023-12-14 16:23 UTC, mehm8128 commented on src/features/traq/stamps.ts
![must](https://img.shields.io/badge/review-must-red.svg)
サーバーからもうデータ返ってくるので実際に通信してほしいです

2023-12-14 16:23 UTC, mehm8128 commented on src/features/traq/users.ts
![must](https://img.shields.io/badge/review-must-red.svg)
こっちも

2023-12-14 16:23 UTC, mehm8128 commented on src/features/traq/users.ts
> +type user = {
![should](https://img.shields.io/badge/review-should-important.svg)
ここもPascalCaseで

2023-12-14 16:23 UTC, mehm8128 commented on src/features/traq/stamps.ts
> +async function getStamps(): Promise<stamp[]> {
![should](https://img.shields.io/badge/review-should-important.svg)
`get～`だと結構軽くデータを加工する感じのイメージなので、通信する場合は`fetch～`でお願いします

2023-12-15 14:13 UTC, ikura-hamu commented on src/features/fabric/components/stamps/util.ts
> +	}
合ってなかったです。空配列返します

2023-12-15 16:48 UTC, mehm8128 requested changes

2023-12-15 16:48 UTC, mehm8128 commented on src/features/fabric/components/stamps/useStamp.ts
> +			height: h
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
でかすぎる気がするので他の図形と同じくらいでいい気がします

2023-12-15 16:48 UTC, mehm8128 commented on src/features/fabric/components/stamps/util.ts
> +	}
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
これでもよさそうです
```suggestion
	if (query === '' || query === '@') return []
```

2023-12-15 16:48 UTC, mehm8128 commented on src/features/fabric/components/stamps/util.ts
> +
![should](https://img.shields.io/badge/review-should-important.svg)
クエリが1文字のとき(僕のPCだと)めっちゃ重いので、できれば1文字のときはちょうどマッチしてるもの以外出さないようにしてほしいです

2023-12-15 16:48 UTC, mehm8128 commented on src/features/fabric/components/stamps/StampSelector.tsx
> +					<span title={''.concat(stamp.isUser ? '@' : '', stamp.name)}>
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
この方が好みかな
```suggestion
					<span title={`${stamp.isUser ? '@' : ''}${stamp.name}`}>
```

2023-12-15 16:48 UTC, mehm8128 commented on src/features/traq/stamps.ts
> +	return unicodeData.concat(originalData)
![should](https://img.shields.io/badge/review-should-important.svg)
4回awaitしてるけど、Promise.allでいい感じにまとめて2回とかにできそうな気がします

2023-12-15 16:48 UTC, mehm8128 commented on src/features/fabric/components/stamps/StampSelector.tsx
> +				{selectedStamps.map(stamp => (
![must](https://img.shields.io/badge/review-must-red.svg)
高さ固定してて、スタンプの数が少なくてその高さに達しないときに隙間が多くなっちゃってます
`h-64`じゃなくて`max-h-64`にするとよさそう？
![image](https://github.com/traP-jp/h23w_01-frontend/assets/83744975/332d775a-433e-4e14-8aaf-f0e80b4a0da2)

2023-12-15 16:48 UTC, mehm8128 commented on src/features/fabric/components/stamps/StampSelector.tsx
> +					<span title={''.concat(stamp.isUser ? '@' : '', stamp.name)}>
spanじゃなくて直接buttonにつけた方がいい気がします
spanタグは消しちゃってよさそう

2023-12-15 16:48 UTC, mehm8128 commented on next.config.js
> +			} // TODO: アイコン取ってくる用。バックエンドの実装ができたら消す
![should](https://img.shields.io/badge/review-should-important.svg)
これもう消せそうですかね

2023-12-16 04:03 UTC, merged