フォームの実装
traP-jp/h23w_01-frontend pull request #5
Opened 2023-12-11 13:29 UTC by ikura-hamu

場所は後で直します

起動するとまだエラー出てる。

```
Hydration failed because the initial UI does not match what was rendered on the server.
```

2023-12-11 16:34 UTC, mehm8128 requested changes
動いてはいそうですが、最初だし時間あるのでそこそこちゃんとレビューしてみました
react-hook-form最後に使ったのそこそこ前であんまり記憶ないのでもうちょっとちゃんと見て追加するかもです:pray:

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +import * as z from 'zod'
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
多分こっちの方がパフォーマンスいいです(ちゃんとパフォーマンス考えるならvalibot使った方がいいですが)

```suggestion
import { z } from 'zod'
```

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +							<FormDescription>送信日時を指定します</FormDescription>
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
なくても分かるので消しちゃっていい気がします(メッセージの方も)

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +	}
![should](https://img.shields.io/badge/review-should-important.svg)
`<ul>`ごとコンポーネントとして切り出してほしいです

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +				<Label key={channel} htmlFor="cancel">
![should](https://img.shields.io/badge/review-should-important.svg)
`Label`の`htmlFor`と`Button`の`id`を`cancel`に設定していますが、これだと`selectedChannels.map`で回している全ての`li`で同じidになってしまいます
idは重複してはいけないので直してほしいです
Reactの[`useId`](https://react.dev/reference/react/useId)というhooksを使うと、1つのコンポーネントに対して一意のidを生成してくれるので、コンポーネントに切り出してそれを使うといいです

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +				<Label key={channel} htmlFor="cancel">
![ask](https://img.shields.io/badge/review-ask-blue.svg)
`Label`につけている`key`ってどういう意味で使っていますか？特にどこにも影響しない気がしました

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +					variant="outline"
![should](https://img.shields.io/badge/review-should-important.svg)
枠線ない方がよさそうです
ここはshadcn/uiのコンポーネントにこだわらずに、Figma見ながら自前実装の方がいいかもです

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +					<Label>...</Label>
![should](https://img.shields.io/badge/review-should-important.svg)
`Label`はフィールドと関連づけて使うものなので、単に`div`とかがよさそうです
ただ、ここは何も表示しなくてもよさそうなので`return null`とかでもいいかもです

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +								/>
![should](https://img.shields.io/badge/review-should-important.svg)
この`watch`はパフォーマンス悪いので、`useWatch`を使った方がいいですね
単純に`render`propsの引数で渡されている`field`を使って書き換えるのって難しそうですかね？

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +				</Label>{' '}
![should](https://img.shields.io/badge/review-should-important.svg)
` `でスペース確保するのあんまりよくないので、できれば`<li>`に`flex justify-between`とかつけて対応してほしいです

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +const nextYear = new Date().getFullYear() + 1
![should](https://img.shields.io/badge/review-should-important.svg)
これ中に直接書いちゃってもそんなに問題ない気がします

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +			message: values.message ? values.message : ''
![should](https://img.shields.io/badge/review-should-important.svg)
空のときnullにしてほしいです
```suggestion
			message: values.message ? values.message : null
```

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +	}),
![should](https://img.shields.io/badge/review-should-important.svg)
`input`要素に`min`指定することでそもそも選択できないようにできそうなのでそうしてほしいです(もちろんその上でこのバリデーションもあってokです)
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/datetime-local

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +		.max(3, { message: 'チャンネルは3つまで指定できます' }),
![should](https://img.shields.io/badge/review-should-important.svg)
ここのmaxも同じく、ロジックでそもそも4つ以上選択できないようにできると思います

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +		.max(100, { message: 'メッセージは100文字以内で入力してください。' })
![should](https://img.shields.io/badge/review-should-important.svg)
これも`textarea`にmax設定できると思います
余裕あったら現在の文字数も出してあげると親切

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +})
![should](https://img.shields.io/badge/review-should-important.svg)
ここのスキーマと59行目の`z.infer<typeof formSchema>`は別ファイルに切り出してほしいです

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/PostForm.ts
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
コンポーネントなくてロジックだけならファイル名lowerCamelでお願いします

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +							role="combobox"
![should](https://img.shields.io/badge/review-should-important.svg)
`combobox`roleはinputタグにつけるものらしいので、ここでは適切ではなさそうです
https://w3c.github.io/aria/#combobox

2023-12-11 16:34 UTC, mehm8128 commented on src/features/form/Form.tsx
> +				</Popover>
![should](https://img.shields.io/badge/review-should-important.svg)
shadcn/ui側でpopoverとcommandを合体させたcomboboxコンポーネントを用意してくれているので、それを使うとよさそうです
https://ui.shadcn.com/docs/components/combobox

2023-12-11 16:36 UTC, mehm8128 requested changes
ページ全体としてのレイアウトは僕が後で整えますが、ここのコンポーネントに収まってる範囲はできるだけFigmaに合わせてほしいです:pray:

2023-12-11 16:36 UTC, mehm8128 commented on src/features/form/Form.tsx
> +							<FormLabel>送信日時</FormLabel>
![must](https://img.shields.io/badge/review-must-red.svg)
あ、必須のところ必須タグつけてほしいです(Figma参照)

2023-12-11 22:44 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +				</Popover>
componentを用意しているわけじゃなくて、PopoverとCommandを組み合わせるとCombobox作れるよって言ってるみたいです。

> The Combobox is built using a composition of the <Popover /> and the <Command /> components.

2023-12-12 00:05 UTC, mehm8128 commented on src/features/form/Form.tsx
> +				</Popover>
ほんとだ、ちゃんと読めてなかった:pray:

2023-12-12 12:32 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +				<Label key={channel} htmlFor="cancel">
copilotに言われるままにつけてました。消しておきます。

2023-12-12 12:35 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +							<FormLabel>送信日時</FormLabel>
必須タグってdivとかで囲ってcss書けばいい感じですか？

2023-12-12 12:42 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +})
`z.infer<typeof formSchema>` を切り出すっていうのは、別のファイルでuseFormを使って、それをimportするってことで合ってますか？

2023-12-12 13:19 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +				<Label key={channel} htmlFor="cancel">
これidをchannelの値にするのはどうですか？

2023-12-12 14:08 UTC, mehm8128 commented on src/features/form/Form.tsx
> +})
型エイリアスを別で定義して、型をimportって感じですね

2023-12-12 14:08 UTC, mehm8128 commented on src/features/form/Form.tsx
> +							<FormLabel>送信日時</FormLabel>
そうですね、divとかspanとかでいいと思います

2023-12-12 14:13 UTC, mehm8128 commented on src/features/form/Form.tsx
> +				<Label key={channel} htmlFor="cancel">
`useId`があるのだから使った方がいいとは思うのですが、まあそれでも今回は問題なさそうなのでどっちでもいいと思います

2023-12-13 07:19 UTC, mehm8128 requested changes
すみませんもうちょっと:pray:
全体的にはnext.js勉強したばかりなのによく書けてると思うので(もちろんcopilotとか使いながらではあると思うけど)
![good](https://img.shields.io/badge/review-good-success.svg)です！

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
> +					</span>
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
`before:content-['・']`じゃなくて`<ul>`に[`list-disc`](https://tailwindcss.com/docs/list-style-type)つけるのがよさそうです(本来ulには勝手についてるのですが、tailwindの[preflight](https://tailwindcss.com/docs/preflight)が消してくれるようになっています)

が、そもそもいらない気がしてきたので消しちゃってもいいです

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
> +					/>
![should](https://img.shields.io/badge/review-should-important.svg)
`onClick`はボタンにつけたいので、`<button>`で`<Cross1Icon>`を囲ってほしいです(そうしないと、別で色々しないとキーボード操作時にフォーカスできないとか色々不都合が出ます)

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/Form.tsx
> +							className="w-[100%] justify-end"
![fyi](https://img.shields.io/badge/review-fyi-informational.svg)
一応これでもできます
```suggestion
							className="w-full justify-end"
```

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
> +	}
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
個人的にはここは関数に分けなくて`return`内に直接書いちゃっていい気がします
長いのが嫌だったら、`<li>`内をさらにコンポーネント分けるか、分けるって言っておいてあれなんですけど`<ul>`とか`Label`は元のコンポーネントのままでもいい気がしてきたので`<li>`だけコンポーネントに分けてある状態がよさそうです

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
> +	const [selectedChannels, setSelectedChannels] = useAtom(selectedChannelsAtom)
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
ここ親子関係でしか使ってないので、多分atom使わなくてもpropsだけで表現できそうです(親で`useState`してgetterとsetter`をpropsで渡す

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
コンポーネントのファイルなのでこれはPascalCaseでお願いします

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/Form.tsx
> +										: 'text-right'
![must](https://img.shields.io/badge/review-must-red.svg)
ここ逆な気がします

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/Form.tsx
> +	const nextYear = new Date().getFullYear() + 1
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
中ってここじゃなくて、変数にしないで`sendDateTime: new Date(`${nextYear}-01-01T00:00:00`),`にそのまま入れてもいいのではって意味でした
まあ名前つけて分かりやすいってメリットはあるし、このままでもよさそうです

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
![must](https://img.shields.io/badge/review-must-red.svg)
`>=`じゃなくて`>`な気がします

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/Form.tsx
> +								<Textarea {...field} maxLength={messageLengthMax} />
そういえばここFigmaで改行なしって話してたから`<Input>`の方がいいかも？

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/formSchema.ts
> +		.optional()
nullは許容するけど入力欄では空文字なので、optional(`undefined`になる可能性がある)ではなさそうです

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/formSchema.ts
> +const messageLengthMax = 100
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
定数なので全部大文字の方がいいかもです
```suggestion
const CHANNELS_MAX = 3
const MESSAGE_LENGTH_MAX = 100
```

2023-12-13 07:19 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
> +			<ul className="list-disc">{makeChannelsList()}</ul>
![should](https://img.shields.io/badge/review-should-important.svg)
他のところと同じようにラベルとフォームの間に8px隙間作ってほしいです
単純にここの親に`space-y-2`だとリストとの間だけになって1つも選択されていないときに隙間がなくなっちゃうので、`<Label>`に`block mb-2`とかがいいかもです
![image](https://github.com/traP-jp/h23w_01-frontend/assets/83744975/f909e6ab-a681-4b45-a3b1-398655dd936f)
![image](https://github.com/traP-jp/h23w_01-frontend/assets/83744975/1fd649d4-020f-43ea-86fc-101c60b6d859)

2023-12-13 09:28 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
maxになったらdisabledになる方が直感的だと思うんですが、どうですか

2023-12-13 09:30 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +								<Textarea {...field} maxLength={messageLengthMax} />
改行無しで100文字まで行っちゃうとかなり横長になりそうですけどいいですかね

2023-12-13 10:26 UTC, mehm8128 commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
maxって言ったら基本その数値はセーフな気がします、HTMLのmaxもそうなってます↓
https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/max

2023-12-13 10:28 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
今の挙動としては、チャンネルが3つ選ばれたらそれ以上選択できなくなっています

2023-12-13 10:30 UTC, mehm8128 commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
あ、そっちのボタンか
送信ボタンかと思ってました:pray:
それなら大丈夫そうです

2023-12-13 10:32 UTC, ikura-hamu commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
確かに保存ボタンも条件満たしてなかったらdisableした方がよさそうですね

2023-12-13 10:37 UTC, mehm8128 commented on src/features/form/Form.tsx
> +											disabled={selectedChannels.length >= channelsMax}
zodでバリデーションするので、そっちはしなくてもいいと思います

2023-12-13 12:41 UTC, mehm8128 commented on src/features/form/selectedChannelsList.tsx
> +					</button>
`onClick`を`button`につけるって意味でした
そうするとアイコンにつけてる`cursor-pointer`も消せるはず

2023-12-13 12:41 UTC, mehm8128 commented on src/features/form/Form.tsx
> +										? field.value.length >= messageLengthMax
100のときはセーフですかね
```suggestion
										? field.value.length > messageLengthMax
```

2023-12-13 12:49 UTC, mehm8128 approved these changes
ありがとうございます！:kansya_kansya:

2023-12-13 12:50 UTC, merged

2023-12-13 14:12 UTC, mehm8128 commented on src/features/form/formSchema.ts
> +	MESSAGE_LENGTH_MAX as messageLengthMax,
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
(書き忘れてたので一応)
ここ多分一括置換したときに`as`でexportされちゃってるので大文字のままexportした方がよさそうです